import Footer from "@/Components/Footer";
import Form from "@/Components/Form";
import Header from "@/Components/Header";
import Mobile from "@/Components/Mobile";
import SocialMedia from "@/Components/SocialMedia";
import Head from "next/head";
import styles from "../../styles/contact.module.css";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Andrés Céspedes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/eärendil.svg" />
      </Head>
      <Header />
      <section className={styles.main}>
        <Form />
        <SocialMedia />
        <Footer />
        <Mobile />
      </section>
    </>
  );
}
