import Accordion from "@/Components/Accordion";
import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import Mobile from "@/Components/Mobile";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../../styles/portfolio.module.css";

export default function Portfolio({ accordionOpened, toggleAccordionOpened }) {
  const [projects, setProjects] = useState();

  useEffect(() => {
    fetch("/api/projects")
      .then((res) => res.json())
      .then(setProjects);
  }, []);
  return (
    <>
      <Head>
        <title>Andrés Céspedes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ac.png" />
      </Head>
      <Header />
      <section className={styles.main}>
        <h2 className={styles.title}>💼 Portfolio 💼</h2>
        <div>
          {projects?.map((project) => (
            <Accordion
              key={project.title}
              accordionOpened={accordionOpened}
              setAccordionOpened={toggleAccordionOpened}
              {...project}
            />
          ))}
        </div>
      </section>
      <Mobile />
      <Footer />
    </>
  );
}
